# Generated by Django 5.2.6 on 2025-09-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imtihon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstudent',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='groupstudent',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
