# Generated by Django 5.2.6 on 2025-09-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imtihon', '0003_alter_groupstudent_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='start_time',
            field=models.DateField(),
        ),
    ]
